- name: Create Linux User if Not Exist with Sudo Access and Bash Shell
  hosts: cluster-1
  gather_facts: no 
  become: yes  # To execute tasks with administrative privileges
  vars:
    username: infraadmin  # Change this to the desired username
    password: aayush  # Change this to the desired password (encrypted using 'mkpasswd' or a similar tool)
  tasks:
    - name: Check if the user exists
      ansible.builtin.shell:
        cmd: "id -u {{ username }}"
      register: existing_user
      ignore_errors: true

    - name: Create the user if not present
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
      when: existing_user.rc != 0  # Create the user only if it doesn't exist

    - name: Add the user to the sudoers file
      ansible.builtin.lineinfile:
        path: "/etc/sudoers"
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
      when: existing_user.rc != 0  # Add the user to sudoers only if it doesn't exist

    - name: Set the shell to bash for the user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
      when: existing_user.rc != 0  # Set the shell only if the user doesn't exist

    - name: Print a message
      ansible.builtin.debug:
        msg: "User {{ username }} already exists. No action taken."
      when: existing_user.rc == 0  # Print a message if the user already exists
