---
- name: Change User Password
  hosts: cluster-1
  gather_facts: no
  become: yes  # To execute tasks with administrative privileges
  vars:
    new_password: "redhat"  # Change this to the desired new password
  tasks:
    - name: Change password for the user
      ansible.builtin.user:
        name: root  # Change this to the username for which you want to change the password
        password: "{{ new_password | password_hash('sha512') }}"  # Hash the password using SHA-512ani